### ISSUE TITLE
Feat: Update cfd-core version

### ISSUE THREAD

**Issue by dillionverma** [cryptogarageinc/cfd-js#257]
# Overview

Hi,
Can we update the cfd-core version to 0.4.3 https://github.com/cryptogarageinc/cfd-core/pull/327 which supports the latest version of libwally?

# Completion condition

- [x] cfd-js has the latest version of cfd-core and can run the latest version of libwally

**Comment by k-matsuzawa** [comment]
Hello.
Thank you for your request. I will release it today!

**Comment by k-matsuzawa** [comment]
@dillionverma 
Hi,
Released cfd-js v0.4.1 which supports the latest version of libwally!
https://github.com/cryptogarageinc/cfd-js/releases/tag/v0.4.1
https://github.com/cryptogarageinc/cfd-js-wasm/releases/tag/v0.4.1

**Comment by dillionverma** [comment]
Thank you @k-matsuzawa! Really appreciate the prompt response :)
